### ISSUE TITLE
Why is it necessary to run reproduce.py with sudo-command?

### ISSUE THREAD

**Issue by taaursland** [econ-ark/QuARK#17]
Does this have something to do with how Docker was installed? Can I fix this, or something for the creator of reproduce.py or the virtual machine?

**Comment by MridulS** [comment]
if you are inside the virtual machine you need to install docker in a specific way as Linux has some peculiarities.

from reproduce-instructions.md

>  - If you are using linux and getting permission errors make sure docker is properly installed, https://docs.docker.com/install/linux/linux-postinstall/

**Comment by taaursland** [comment]
Thank you.
